server:
  port: 7070

spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: hr
    password: hr
  jpa:
    show-sql: true
  application:
    name: donor-service
    
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  endpoint:
    shutdown:
      enabled: true

info:
   build:
    artificatId: '@project.artifact@'
    groupId: '@project.groupid@'
   java:
     version: 8.0

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

